/**
 * Honest provenance disclosure. The existing mock intelligence generator
 * (`chatService.js`) does not produce a confidence score or model identity —
 * it is a template/keyword engine, not a model — so this states that plainly
 * rather than fabricating a number. Keeps the Intelligence section from ever
 * being mistaken for a verified operational fact.
 */
export default function IntelligenceProvenance({ status }) {
  if (status !== "ready") return null;

  return (
    <section className="koi-card intel-provenance">
      <h3 className="card-label">Provenance</h3>
      <p className="muted">
        Generated by KOI's mock intelligence engine (demo templates, not a live AI model). No
        confidence score is available yet — treat this as a starting interpretation to verify
        against the operational context above, not a finished decision.
      </p>
    </section>
  );
}
