import { parse } from "csv-parse/sync";
import { Guest } from "../../models/Guest.js";
import { ImportBatch } from "../../models/ImportBatch.js";
import { Property } from "../../models/Property.js";
import { Stay } from "../../models/Stay.js";
import { Unit } from "../../models/Unit.js";
import { Workspace } from "../../models/Workspace.js";
import { AppError } from "../../utils/AppError.js";
import { requireObjectId } from "../../utils/objectId.js";
import {
  assertExists,
  duplicateKeyMessage,
  findInWorkspaceOr404,
  isDuplicateKeyError,
  toPlain,
} from "../queryHelpers.js";
import {
  assertNoDuplicateHeaders,
  buildDateParser,
  clip,
  mapRow,
  resolveStatus,
  validateMappingProfile,
  validateStatusMapping,
} from "./columnMapping.js";

/**
 * Phase 7F-E — eZee CSV operational data import.
 *
 * eZee CSV -> parse -> normalized rows -> deterministic mapping profile ->
 * row normalization/validation -> Guest upsert -> Stay upsert -> ImportBatch
 * audit -> aggregate result. Operational data lands exclusively in the
 * existing Guest/Stay MongoDB models (via their existing unique partial
 * indexes on externalId/reservationId) — nothing here touches
 * KnowledgeDocument/KnowledgeChunk/embeddings/RAG, calls no LLM, and no
 * Signal is generated by an import (see CLAUDE.md's AI/RAG boundaries and
 * the phase's own design report).
 *
 * Rows are processed sequentially, not in parallel: this is what makes
 * "last row wins" for a duplicate reservationId within one file fall out
 * naturally (each row's upsert sees the previous row's write).
 *
 * Write ordering / partial-write behavior (no transactions on purpose — the
 * dev MongoDB is a standalone instance, and there is no compensation logic):
 *  1. Every validation (mapping, dates, status, unit, immutability, required
 *     new-Stay fields, merged date range, Mongoose schema validate()) runs
 *     BEFORE any write, so a row that fails validation writes nothing.
 *  2. The Guest is saved first, then the Stay. If the Guest save succeeds and
 *     the Stay save then fails (DB-level error only), the Guest remains and
 *     the row is reported failed.
 *  3. Re-running is idempotent: the retry finds that Guest by
 *     (workspaceId, externalId) and reuses it — no duplicate Guest — then
 *     creates the Stay. A duplicate-key race on either save is retried (bounded, up to 5 attempts).
 *
 * Design choices (approved in 7F-E review):
 *  - A blank mapped cell never erases an existing non-empty value.
 *  - Imported Stays deliberately do NOT run stayService's manual-entry
 *    overlap/double-booking guard (externally-sourced facts are recorded as
 *    they happened, not rejected by an internal data-entry safeguard).
 */

class RowError extends Error {}

/** Caps persisted/returned per-row diagnostics so a huge bad file cannot bloat the ImportBatch document or response. */
const MAX_RECORDED_ISSUES = 1000;
const MAX_FILENAME_LENGTH = 255;

const GUEST_FIELD_TARGETS = {
  "guest.firstName": "firstName",
  "guest.lastName": "lastName",
  "guest.email": "email",
  "guest.phone": "phone",
};

function parseNonNegativeInt(value, label) {
  if (value === undefined || value === null || value === "") return undefined;
  if (!/^\d{1,4}$/.test(value)) {
    throw new RowError(`Invalid ${label} value`);
  }
  return Number(value);
}

/** Basename only, bounded — never persist a client-supplied path. */
function sanitizeFilename(name) {
  const base = String(name ?? "").split(/[\\/]/).pop().replace(/[\u0000-\u001f]/g, "").trim();
  return base.slice(0, MAX_FILENAME_LENGTH);
}

async function resolveUnitId(propertyId, roomNumber) {
  if (roomNumber === undefined || roomNumber === null || roomNumber === "") return undefined;
  // propertyId was already proven to belong to the workspace; a Unit is only
  // ever resolved through that Property, never by unitNumber alone.
  const unit = await Unit.findOne({ propertyId, unitNumber: roomNumber });
  if (!unit) {
    throw new RowError(`Unit not found for property: "${clip(roomNumber)}"`);
  }
  return unit._id;
}

/**
 * Validates everything about one row and builds (but does not save) the
 * Guest/Stay documents, so a row that is going to fail never leaves a
 * partial write behind. Only DB-level failures during the final saves (e.g.
 * a unique-index race) can still interrupt after the first save.
 *
 * Natural keys are always workspace-scoped: (workspaceId, externalId) for
 * Guest, (workspaceId, reservationId) for Stay.
 */
async function processRow({ workspaceId, propertyId, mappingProfile, parseDate, statusMapping, rawRow }) {
  const mapped = mapRow(rawRow, mappingProfile);

  const allBlank = Object.values(mapped).every((value) => value === undefined || value === "");
  if (allBlank) {
    return { outcome: "skipped" };
  }

  const reservationId = mapped["stay.reservationId"];
  if (!reservationId) throw new RowError("Missing required stay.reservationId");
  const externalId = mapped["guest.externalId"];
  if (!externalId) throw new RowError("Missing required guest.externalId");

  let checkIn;
  if (mapped["stay.checkIn"]) {
    checkIn = parseDate(mapped["stay.checkIn"]);
    if (checkIn === null) throw new RowError("Invalid stay.checkIn date");
  }

  let checkOut;
  if (mapped["stay.checkOut"]) {
    checkOut = parseDate(mapped["stay.checkOut"]);
    if (checkOut === null) throw new RowError("Invalid stay.checkOut date");
  }

  let status;
  if (mapped["stay.status"]) {
    status = resolveStatus(statusMapping, mapped["stay.status"]);
    if (status === undefined) {
      throw new RowError(`Unknown status value: "${clip(mapped["stay.status"])}"`);
    }
  }

  const adults = parseNonNegativeInt(mapped["stay.adults"], "stay.adults");
  const children = parseNonNegativeInt(mapped["stay.children"], "stay.children");
  const unitId = await resolveUnitId(propertyId, mapped["stay.roomNumber"]);

  const existingStay = await Stay.findOne({ workspaceId, reservationId });
  const existingGuest = await Guest.findOne({ workspaceId, externalId });

  if (existingStay) {
    // guestId/propertyId are immutable after creation (same as stayService's
    // UPDATABLE list) — a conflicting row fails loudly instead of either
    // silently rewriting the link or silently ignoring the mismatch.
    if (String(existingStay.propertyId) !== String(propertyId)) {
      throw new RowError("Reservation belongs to a different property");
    }
    if (!existingGuest || String(existingStay.guestId) !== String(existingGuest._id)) {
      throw new RowError("Reservation belongs to a different guest");
    }
  } else {
    // A NEW Stay must be fully specified: never silently default the status
    // to the schema's "reserved", and never create a stay without a unit or
    // a date range. (An existing Stay may leave these blank to retain them.)
    if (!status) throw new RowError("Missing required stay.status for a new reservation");
    if (unitId === undefined) throw new RowError("Missing required stay.roomNumber for a new reservation");
    if (!checkIn) throw new RowError("Missing required stay.checkIn for a new reservation");
    if (!checkOut) throw new RowError("Missing required stay.checkOut for a new reservation");
  }

  const guest = existingGuest ?? new Guest({ workspaceId, externalId });
  // Non-empty values only: a blank cell never erases previously-known data.
  for (const [target, field] of Object.entries(GUEST_FIELD_TARGETS)) {
    const value = mapped[target];
    if (value !== undefined && value !== "") guest[field] = value;
  }

  const stay = existingStay ?? new Stay({ workspaceId, reservationId, guestId: guest._id, propertyId });
  if (unitId !== undefined) stay.unitId = unitId;
  if (checkIn !== undefined) stay.checkIn = checkIn;
  if (checkOut !== undefined) stay.checkOut = checkOut;
  if (status !== undefined) stay.status = status;
  if (adults !== undefined) stay.adults = adults;
  if (children !== undefined) stay.children = children;

  // Range is checked on the merged result, so a row supplying only one date
  // cannot produce an inverted range against the stored other date.
  if (stay.checkIn && stay.checkOut && stay.checkOut <= stay.checkIn) {
    throw new RowError("checkOut must be after checkIn");
  }

  await guest.validate();
  await stay.validate();

  await guest.save();
  await stay.save();

  return { outcome: existingStay ? "updated" : "created", reservationId };
}

/**
 * Bounded retry on a duplicate-key error: it means a concurrent writer just
 * created the same natural key, so re-running the row finds and updates it.
 * Several simultaneous writers can each lose in turn, hence more than one
 * retry — but always bounded, and any other error is never retried.
 */
const MAX_DUPLICATE_KEY_ATTEMPTS = 5;

async function processRowWithRetry(args) {
  for (let attempt = 1; ; attempt += 1) {
    try {
      return await processRow(args);
    } catch (error) {
      if (!isDuplicateKeyError(error) || attempt >= MAX_DUPLICATE_KEY_ATTEMPTS) throw error;
    }
  }
}

function rowErrorMessage(error) {
  if (error instanceof RowError) return error.message;
  if (error instanceof AppError) return error.message;
  if (isDuplicateKeyError(error)) return duplicateKeyMessage(error);
  return "Row could not be processed";
}

export async function importOperationalCsv({
  workspaceId: rawWorkspaceId,
  propertyId: rawPropertyId,
  filename,
  buffer,
  mappingProfile: rawMappingProfile,
  dateFormat,
  statusMapping: rawStatusMapping,
}) {
  // Tenant validation happens first, before the file or any operational
  // collection is touched. The validated locals below are the only ids used
  // for the rest of the import.
  if (typeof rawWorkspaceId !== "string" || typeof rawPropertyId !== "string") {
    throw new AppError("workspaceId and propertyId are required", 400);
  }
  const workspaceId = requireObjectId(rawWorkspaceId, "workspaceId");
  await assertExists(Workspace, workspaceId, "Workspace");

  const propertyId = requireObjectId(rawPropertyId, "propertyId");
  await findInWorkspaceOr404(Property, propertyId, workspaceId, "Property");

  if (!buffer || buffer.length === 0) {
    throw new AppError("Uploaded file is empty", 400);
  }

  let headerRow;
  try {
    [headerRow] = parse(buffer, { bom: true, trim: true, to_line: 1 });
  } catch (error) {
    throw new AppError(`Malformed CSV file (${error.code || "parse error"})`, 400);
  }
  if (!headerRow || headerRow.length === 0) {
    throw new AppError("CSV file has no header row", 400);
  }

  // File-level checks must all pass before any row is touched. Duplicate
  // headers make column mapping ambiguous, so the whole file is rejected here
  // (nothing written, no ImportBatch created).
  assertNoDuplicateHeaders(headerRow);
  const mappingProfile = validateMappingProfile(rawMappingProfile, headerRow);
  const parseDate = buildDateParser(dateFormat);
  const statusMapping = validateStatusMapping(rawStatusMapping);

  let rows;
  try {
    rows = parse(buffer, { columns: true, bom: true, trim: true, skip_empty_lines: true });
  } catch (error) {
    throw new AppError(`Malformed CSV file (${error.code || "parse error"})`, 400);
  }

  const importBatch = await ImportBatch.create({
    workspaceId,
    propertyId,
    filename: sanitizeFilename(filename),
    sourceType: "csv",
    status: "pending",
    startedAt: new Date(),
    rowsRead: rows.length,
    // The validated/normalized profile (≤12 allowed keys, bounded values), not the raw request object.
    mappingProfile,
  });
  const batchScope = { _id: importBatch._id, workspaceId };

  try {
    const errors = [];
    const warnings = [];
    let rowsCreated = 0;
    let rowsUpdated = 0;
    let rowsSkipped = 0;
    let rowsFailed = 0;
    const seenReservationIds = new Set();

    for (let index = 0; index < rows.length; index += 1) {
      const rowNumber = index + 2; // header occupies line 1

      try {
        const result = await processRowWithRetry({
          workspaceId,
          propertyId,
          mappingProfile,
          parseDate,
          statusMapping,
          rawRow: rows[index],
        });

        if (result.outcome === "skipped") {
          rowsSkipped += 1;
          continue;
        }

        if (seenReservationIds.has(result.reservationId) && warnings.length < MAX_RECORDED_ISSUES) {
          warnings.push(
            `Row ${rowNumber}: duplicate reservationId "${clip(result.reservationId)}" in file — later row takes precedence`,
          );
        }
        seenReservationIds.add(result.reservationId);

        if (result.outcome === "created") rowsCreated += 1;
        else rowsUpdated += 1;
      } catch (error) {
        rowsFailed += 1;
        if (errors.length < MAX_RECORDED_ISSUES) {
          errors.push({ row: rowNumber, message: rowErrorMessage(error) });
        }
      }
    }

    if (rowsFailed > errors.length) {
      warnings.push(`Only the first ${errors.length} of ${rowsFailed} row errors were recorded`);
    }

    const completedAt = new Date();
    // Scoped write by (_id, workspaceId), never by _id alone.
    await ImportBatch.updateOne(batchScope, {
      $set: { status: "completed", completedAt, rowsCreated, rowsUpdated, rowsSkipped, rowsFailed, errors },
    });

    return {
      importBatchId: String(importBatch._id),
      status: "completed",
      rowsRead: rows.length,
      rowsCreated,
      rowsUpdated,
      rowsSkipped,
      rowsFailed,
      errors,
      warnings,
    };
  } catch (fatal) {
    // Unexpected failure outside per-row handling: leave an honest audit
    // trail (failed + completedAt) where possible, then surface the error.
    try {
      await ImportBatch.updateOne(batchScope, { $set: { status: "failed", completedAt: new Date() } });
    } catch {
      // best effort only
    }
    throw fatal;
  }
}

export async function getImportBatchById(id, workspaceId) {
  const scope = requireObjectId(workspaceId, "workspaceId");
  return toPlain(await findInWorkspaceOr404(ImportBatch, requireObjectId(id), scope, "ImportBatch"));
}
